browsers:
  user_agents:
    linux_firefox: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0"
    linux_konqueror: "Mozilla/5.0 (compatible; Konqueror/3; Linux)"
    linux_mozilla: "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.4) Gecko/20030624"
    mac_firefox: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:26.0) Gecko/20100101 Firefox/26.0"
    mac_mozilla: "Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.4a) Gecko/20030401"
    mac_safari4: "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_2; de-at) AppleWebKit/531.21.8 (KHTML, like Gecko) Version/4.0.4 Safari/531.21.10"
    mac_safari: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.73.11 (KHTML, like Gecko) Version/7.0.1 Safari/537.73.11"
    windows_chrome: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.32 Safari/537.36"
    windows_ie6: "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)"
    windows_ie7: "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
    windows_ie8: "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
    windows_ie9: "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)"
    windows_ie10: "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)"
    windows_ie11: "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
    windows_mozilla: "Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.4b) Gecko/20030516 Mozilla Firebird/0.6"
    windows_firefox: "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0"
    iphone: "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53"
    ipad: "Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53"
    android: "Mozilla/5.0 (Linux; Android 4.4.2; Nexus 7 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.59 Safari/537.36"
  user_agents_mechanize:
    linux_firefox: 'Linux Firefox'
    linux_konqueror: 'Linux Konqueror'
    linux_mozilla: 'Linux Mozilla'
    mac_firefox: 'Mac Firefox'
    mac_mozilla: 'Mac Mozilla'
    mac_safari4: 'Mac Safari 4'
    mac_safari: 'Mac Safari'
    windows_chrome: 'Windows Chrome'
    windows_ie6: 'Windows IE 6'
    windows_ie7: 'Windows IE 7'
    windows_ie8: 'Windows IE 8'
    windows_ie9: 'Windows IE 9'
    windows_ie10: 'Windows IE 10'
    windows_ie11: 'Windows IE 11'
    windows_mozilla: 'Windows Mozilla'
    windows_firefox: 'Windows Firefox'
    iphone: 'iPhone'
    ipad: 'iPad'
    android: 'Android'
